#!/bin/sh

start() {
    modprobe fbtft_device name=adafruit22a gpios="reset:145,dc:144" busnum=0
    /root/appstart.sh
}
stop() {
	echo "OK"
}
restart() {
	stop
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

